eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
   instance:
    hostname: localhost
microservice:
  CreateEmployee:
    endpoints:
      endpoint:
        uri:http://localhost:9090/api/employee/create
  AddEmployee:
    endpoints:
      endpoint:
        uri:http://localhost:9091/api/employee/create
 
